{% set data= load_setup_py_data() %}
package:
  name: ts-mteec
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_mteec = lsst.ts.mteec.mteec_csc:run_mteec

test:
  requires:
    - ts-conda-build =0.4
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
    - ts-dds
  source_files:
    - python
    - bin
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - py.test

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
  build:
    - python {{ python }}
    - setuptools_scm
    - setuptools
    - ts-conda-build =0.4
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
